#!/usr/bin/env bash
# This script installs and configures nginx

sudo su
apt-get update
apt-get install -y nginx

echo "Hello World!" > /var/www/html/index.html

sudo service nginx restart
sudo service nginx start
