#!/usr/bin/env bash
# This script installs and configures nginx

sudo su
apt-get update -y
apt-get install -y nginx

echo "Hello World!" > /var/www/html/index.html
echo "server {
    server_name farrhouqbnb.tech;
    rewrite /redirect_me https://youtube.com/watch?v=QH@-TGUlwu4 permanent;
}
" > /etc/nginx/sites-available/default

sudo service nginx restart
sudo service nginx start
