#!/usr/bin/env bash
# This script installs and configures nginx

sudo su
apt-get update -y
apt-get install -y nginx

echo "Hello World!" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html

echo "server {
    server_name 490305-web-02;
    rewrite /redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 redirect;


    location / {
        try_files \$uri \$uri/ =404;
        add_header X-Served-By $HOSTNAME;
    }         

                                                        
    error_page 404 /custom_404.html;
        location = /custom_404.html {
                root /usr/share/nginx/html;
                internal;
        }
}" > /etc/nginx/sites-available/default



sudo service nginx restart
sudo service nginx start
