#!/usr/bin/env bash
# Does some stuff.
echo $$ > /var/run/myscript.pid
while true; do
    echo "To infinity and beyond"

    hate_kill() {
        echo "I hate the kill command"
    }

    no_love() {
        echo "Y U no love me?!"
    }

    delete_self() {
        rm /var/run/myscript.pid
        exit
    }

    trap 'hate_kill' SIGTERM
    trap 'no_love' SIGINT
    trap 'delete_self' SIGQUIT
    trap 'delete_self' SIGTERM

done
