#!/usr/bin/env bash
# This manages the manage_my_process file processes
start() {
    ./manage_my_process &
    pid=$!
    echo "$pid" > /var/run/my_process.pid
    echo "manage_my_process started"
}

stop () {
    kill "$pid"
    rm /var/run/my_process.pid
    echo "manage_my_process stopped"
}

restart () {
    kill "$pid"
    rm /var/run/my_process.pid
    ./manage_my_process &
    pid=$!
    echo "$pid" > /var/run/my_process.pid
    echo "manage_my_process restarted"
}


case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        restart
        ;;
    *)
        echo "Usage: manage_my_process {start|stop|restart}"
        exit 1
        ;;
esac
