#!/usr/bin/env bash
# This script displays "To infinity and beyond" infinitely
while true; do
    echo "To infinity and beyond"
    sleep 2

    invicible() {
        echo "I am invincible!!!"
    }

    trap 'invicible' SIGTERM
done
