#!/usr/bin/env bash
# This script is fizzbuzz
for ((i = 1; i <= 100; i++)); do
    if [ $(($i % 15)) -eq 0 ]; then
        echo "fizzbuzz"
    elif [ $(($i % 3)) -eq 0 ]; then
        echo "fizz"
    elif [ $(($i % 5)) -eq 0 ]; then
        echo "buzz"
    fi
done
