#!/usr/bin/env bash
# This script is displaying "Best School" 10 times and Hi 9
hour=0
minute=1
while [ $hour -lt 12 ]; do
    echo "Hour: $hour"
    minute=1
    while [ $minute -lt 60 ]; do
        echo $minute 
        ((minute++))
    done
    ((hour++))
done
